// <auto-generated />
using System;
using BookingService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingService.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20190921063109_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingService.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airlines")
                        .HasColumnName("airlines");

                    b.Property<bool>("Booked")
                        .HasColumnName("booked");

                    b.Property<string>("Class")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("createdAt");

                    b.Property<int>("GuestNum")
                        .HasColumnName("guestNum");

                    b.Property<string>("TripType")
                        .HasColumnName("tripType");

                    b.HasKey("Id");

                    b.ToTable("flight");
                });

            modelBuilder.Entity("BookingService.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Booked")
                        .HasColumnName("booked");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("createdAt");

                    b.Property<int>("GuestNum")
                        .HasColumnName("guestNum");

                    b.Property<string>("HotelName")
                        .HasColumnName("hotelName");

                    b.Property<string>("RoomType")
                        .HasColumnName("roomType");

                    b.HasKey("Id");

                    b.ToTable("hotel");
                });
#pragma warning restore 612, 618
        }
    }
}
